/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package curdApp;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author amilawickramarathne
 */
public class curdApp extends javax.swing.JFrame {
 private static final String userName= "root";
    private static final String passWord= "Ebba@123";
        private static final String dbName= "jdbc:mysql://127:0:0:0:3306/curdAssigment";
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        int q,id;
    /**
     * Creates new form curdApp
     */
    public curdApp() {
        initComponents();
        updateDb();
    }
    
    public void updateDb(){
     try {
         Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
         try {
             Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/curdAssigment","root","Ebba@123");
             pst = con1.prepareStatement("select * from Employee_data");
             rs = pst.executeQuery();
             ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
             q = stData.getColumnCount();
             DefaultTableModel RecordTable = (DefaultTableModel)Table.getModel();
             RecordTable.setRowCount(0);
             
             while(rs.next()){
                 Vector columnData = new Vector();
                 for(int i=1;i<=q;i++){
                     columnData.add(rs.getString("employeeID"));
                     columnData.add(rs.getString("Name"));
                     columnData.add(rs.getString("ContactNumber"));
                     columnData.add(rs.getString("Salary"));
                     
                 }
                 RecordTable.addRow(columnData);
             }
             
             
             
         } catch (SQLException ex) {
             Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
         }
     } catch (ClassNotFoundException ex) {
         JOptionPane.showMessageDialog(null, ex);
         Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
         Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
         Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
     }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        emy_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contactNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee ID");

        emy_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emy_IdActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel3.setText("Contact No");

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });

        jLabel4.setText("Salary");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "Name", "Contact No", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(emy_Id)
                            .addComponent(contactNo)
                            .addComponent(salary))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton4)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emy_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            try {
                // TODO add your handling code here:
               // Class.forName("com.mysql.jdbc.Driver");
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            } catch (ClassNotFoundException ex) {
                System.out.println(ex);
                //Logger.getLogger(crdForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                 Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IllegalAccessException ex) {
                 Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
             }
             Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/curdAssigment","root","Ebba@123");
            //stat = con1.prepareStatement("select * form employe_table");
            String sql = "insert into Employee_data(employeeID,Name,ContactNumber,Salary) values(?,?,?,?)";
           // stat = con1.prepareStatement("inster into Employee_data(employeeID,Name,ContactNumber,Salary) VALUES ('"+"ssssss"+"','"+"ssssss"+"','"+"ssssss"+"','"+"ssssss"+"')");
           PreparedStatement ps = con1.prepareCall(sql);
           
           ps.setString(1, emy_Id.getText());
           ps.setString(2, name.getText());
           ps.setString(3, contactNo.getText());
           ps.setString(4, salary.getText());
           ps.execute();
           JOptionPane.showConfirmDialog(null, "Record added succefully","Info",JOptionPane.YES_NO_OPTION);
           updateDb();
          
           

        } catch (SQLException ex) {
            System.out.println(ex);
           // Logger.getLogger(crdForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emy_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emy_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emy_IdActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel RecordTable = (DefaultTableModel)Table.getModel();
        int SelectRows = Table.getSelectedRow();
        emy_Id.setText(RecordTable.getValueAt(SelectRows, 0).toString());
        name.setText(RecordTable.getValueAt(SelectRows, 1).toString());
        contactNo.setText(RecordTable.getValueAt(SelectRows, 2).toString());
        salary.setText(RecordTable.getValueAt(SelectRows, 3).toString());
      
        //RecordTable.setRowCount(0);
    }//GEN-LAST:event_TableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)Table.getModel();
        int SelectRows = Table.getSelectedRow();
        
        id = Integer.parseInt(RecordTable.getValueAt(SelectRows, 0).toString());
     try {
            try {
              //  "insert into Employee_data(employeeID,Name,ContactNumber,Salary) values(?,?,?,?)"
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                Connection sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/curdAssigment","root","Ebba@123");
                pst = sqlConn.prepareStatement("update Employee_data set employeeID =?, Name =?,ContactNumber =?, Salary=? where employeeID=?");
                pst.setString(1, emy_Id.getText());
                pst.setString(2, name.getText());
                pst.setString(3, contactNo.getText());
                pst.setString(4, salary.getText());
                pst.setString(5, emy_Id.getText());
                
                pst.executeUpdate();
                JOptionPane.showConfirmDialog(null, "Record Updated","Info",JOptionPane.YES_NO_OPTION);

               // JOptionPane.showConfirmDialog(this, "Record Updated");
                updateDb();
                
                
                
                
            } catch (InstantiationException ex) {
                Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
            }
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
         
     }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)Table.getModel();
        int SelectRows = Table.getSelectedRow();
        
        id = Integer.parseInt(RecordTable.getValueAt(SelectRows, 0).toString());
        try {
            try {
                
                int deletedItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete item","Warning",JOptionPane.YES_NO_OPTION);
                if(deletedItem == JOptionPane.YES_OPTION)
                {
                 Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                Connection sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/curdAssigment","root","Ebba@123");
                pst = sqlConn.prepareStatement("delete from Employee_data  where employeeID=?");
                pst.setString(1, emy_Id.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Student Recode Deleted");
                updateDb();
                
                //                pst = sqlConn.prepareStatement("update Employee_data set employeeID =?, Name =?,ContactNumber =?, Salary=? where employeeID=?");
                pst.setString(1, "");
                pst.setString(2, "");
                pst.setString(3, "");
                pst.setString(4, "");
                pst.setString(5, "");
                
                }
              //  "insert into Employee_data(employeeID,Name,ContactNumber,Salary) values(?,?,?,?)"
//                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
//                Connection sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/curdAssigment","root","Ebba@123");
//                pst = sqlConn.prepareStatement("update Employee_data set employeeID =?, Name =?,ContactNumber =?, Salary=? where employeeID=?");
//                pst.setString(1, emy_Id.getText());
//                pst.setString(2, name.getText());
//                pst.setString(3, contactNo.getText());
//                pst.setString(4, salary.getText());
//                pst.setString(5, emy_Id.getText());
//                
//                pst.executeUpdate();
//                JOptionPane.showConfirmDialog(this, "Record Updated");
//                updateDb();
                
                
                
                
            } catch (InstantiationException ex) {
                Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
            }
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(curdApp.class.getName()).log(Level.SEVERE, null, ex);
         
     }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               emy_Id.setText("");
               name.setText("");
               contactNo.setText("");
               salary.setText("");
            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(curdApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(curdApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(curdApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(curdApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new curdApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTextField contactNo;
    private javax.swing.JTextField emy_Id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField salary;
    // End of variables declaration//GEN-END:variables
}
